pipeline {
    agent any
    tools {
        nodejs 'Nodejs'
    }
    environment {
        GITHUB_TOKEN = credentials('111')
    }

    stages {
        stage('Checkout') {
            steps {
                // Thực hiện git pull từ nhánh feature/init-server
                script {
                    checkout([$class: 'GitSCM',
                            branches: [[name: 'feature/init-server']],
                            doGenerateSubmoduleConfigurations: false,
                            extensions: [[$class: 'CleanCheckout']],
                            submoduleCfg: [],
                            userRemoteConfigs: [[url: 'https://github.com/minhtringuyen31/Ads-Management.git']]])
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                // Bước này để cài đặt các dependencies của Node.js
                script {
                    
                    dir('Server') {
                        sh 'npm install'
                    }
                }
            }
        }

        stage('Build') {
            steps {
                // Bước này để thực hiện các bước build hoặc compile (nếu cần)
                script {
                    
                    dir('Server') {
                        sh 'docker build -t web .'
                        sh 'docker rm -f web .'
                        sh 'docker run -p 80:5001 -d --name web web .'
                    }
                }
            }
        }

        

        stage('Deploy') {
            steps {
                // Bước này để triển khai ứng dụng (nếu cần)
                script {
                    // Thay thế lệnh dưới đây bằng lệnh triển khai thực tế của bạn
                    echo 'Deployment step...'
                }
            }
        }
    }

    
}
