const reportTestData = {
  reports: [
    {
      id: 1,
      report_form: 'troubleshooting',
      username: 'Nguyen Van A',
      email: 'nguyenvana@gmail.com',
      phone_number: '0912345678',
      report_content:
        "New York City, often considered the world's advertising capital, is home to a vast array of advertising boards that contribute significantly to the city's vibrant and dynamic atmosphere.\n\nThese boards, ranging from traditional billboards to digital screens, are strategically placed in high-traffic areas such as Times Square, Broadway, and along major highways, capturing the attention of millions of residents and tourists daily.\n\nThe advertising boards in New York are as diverse as the city itself. They display a wide variety of content, from promotions for the latest Broadway shows to advertisements for global brands.\n\nThe rise of digital advertising boards has further revolutionized the industry, allowing for more dynamic, interactive, and time-sensitive content. However, the proliferation of advertising boards also raises concerns about visual pollution and energy consumption.\n\nThe city's authorities have implemented regulations to control the size, location, and brightness of these boards to mitigate their impact on the urban landscape and environment. Despite these challenges, advertising boards remain an integral part of New York's cityscape. They not only serve as a platform for businesses to reach their target audience but also contribute to the city's reputation as a global advertising hub.",
      related_to: 1,
      type: 'location',
      status: 'not_solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
      images: [
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      ],
    },
    {
      id: 2,
      report_form: 'report',
      username: 'Nguyen Van B',
      email: 'nguyenvanb@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 2,
      type: 'location',
      status: 'not_solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
      images: [
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      ],
    },
    {
      id: 3,
      report_form: 'suggest',
      username: 'Nguyen Van C',
      email: 'nguyenvanc@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 3,
      type: 'location',
      status: 'not_solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
      images: [
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      ],
    },
    {
      id: 4,
      report_form: 'troubleshooting',
      username: 'Tran Thi A',
      email: 'nguyenvana@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 1,
      type: 'location',
      status: 'solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
      images: [
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      ],
    },
    {
      id: 5,
      report_form: 'report',
      username: 'Tran Thi B',
      email: 'nguyenvanb@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 2,
      type: 'location',
      status: 'solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
      images: [
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      ],
    },
    {
      id: 6,
      report_form: 'suggest',
      username: 'Tran Thi C',
      email: 'nguyenvanc@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 3,
      type: 'location',
      status: 'solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
      images: [
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      ],
    },
    {
      id: 7,
      report_form: 'troubleshooting',
      username: 'Nguyen Van A',
      email: 'nguyenvana@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 1,
      type: 'ads_board',
      status: 'not_solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
      images: [
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      ],
    },
    {
      id: 8,
      report_form: 'report',
      username: 'Nguyen Van B',
      email: 'nguyenvanb@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 2,
      type: 'ads_board',
      status: 'not_solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
      images: [
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      ],
    },
    {
      id: 9,
      report_form: 'suggest',
      username: 'Nguyen Van C',
      email: 'nguyenvanc@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 3,
      type: 'ads_board',
      status: 'not_solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
      images: [
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      ],
    },
    {
      id: 10,
      report_form: 'troubleshooting',
      username: 'Tran Thi A',
      email: 'nguyenvana@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 1,
      type: 'ads_board',
      status: 'solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
      images: [
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      ],
    },
    {
      id: 11,
      report_form: 'report',
      username: 'Tran Thi B',
      email: 'nguyenvanb@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 2,
      type: 'ads_board',
      status: 'solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
      images: [
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      ],
    },
    {
      id: 12,
      report_form: 'suggest',
      username: 'Tran Thi C',
      email: 'nguyenvanc@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 3,
      type: 'ads_board',
      status: 'solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
      images: [
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      ],
    },
  ],
};

const locationTestData = {
  locations: [
    {
      id: 1,
      latitude: 10.7629462525597,
      longtitude: 106.6824931286189,
      address: '227 Đ. Nguyễn Văn Cừ',
      ward_id: 4,
      area_type: 'Đất công/Công viên/Hành lang an toàn giao thông',
      ads_type: 'Cổ động chính trị',
      image:
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
      is_planned: true,
      isSolvedAll: false,
    },
    {
      id: 2,
      latitude: 10.762881421075154,
      longtitude: 106.68632355086243,
      address: '252 Đ. Nguyễn Trãi',
      ward_id: 4,
      area_type: 'Đất công/Công viên/Hành lang an toàn giao thông',
      ads_type: 'Quảng cáo thương mại',
      image:
        'https://lh5.googleusercontent.com/p/AF1QipMfSoB9juvelPtNK6XMFDxhM7Fj89SNSvrJA4gq=w408-h306-k-no',
      is_planned: false,
      isSolvedAll: true,
    },
    {
      id: 3,
      latitude: 10.76157111596576,
      longtitude: 106.68220011223177,
      address: '280 Đ. An Dương Vương',
      ward_id: 6,
      area_type: 'Đất công/Công viên/Hành lang an toàn giao thông',
      ads_type: 'Xã hội hóa',
      image:
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      is_planned: false,
      isSolvedAll: true,
    },
  ],
};

const wardTestData = {
  wards: [
    {
      id: 1,
      district_id: 5,
      name: 'Phường 1',
    },
    {
      id: 2,
      district_id: 5,
      name: 'Phường 2',
    },
    {
      id: 3,
      district_id: 5,
      name: 'Phường 3',
    },
    {
      id: 4,
      district_id: 5,
      name: 'Phường 4',
    },
    {
      id: 5,
      district_id: 5,
      name: 'Phường 5',
    },
    {
      id: 6,
      district_id: 1,
      name: 'Phường Nguyễn Cư Trinh',
    },
  ],
};

const districtTestData = {
  districts: [
    {
      id: 1,
      name: 'Quận 1',
    },
    {
      id: 2,
      name: 'Quận 2',
    },
    {
      id: 3,
      name: 'Quận 3',
    },
    {
      id: 4,
      name: 'Quận 4',
    },
    {
      id: 5,
      name: 'Quận 5',
    },
  ],
};

const adsBoardTestData = {
  ads_boards: [
    {
      id: 1,
      location_id: 1,
      type: 'Trụ, cụm pano',
      width: 100,
      height: '100',
      contract_end_date: '2023-05-05T02:57:31Z',
      contract_start_date: '2023-05-05T02:57:31Z',
      company: 1,
      amount: '1 trụ/bảng',
    },
    {
      id: 2,
      location_id: 2,
      type: 'Trụ',
      width: 90,
      height: '15',
      contract_end_date: '2023-05-08T02:57:31Z',
      contract_start_date: '2023-05-08T02:57:31Z',
      company: 1,
      amount: '2 trụ/bảng',
    },
    {
      id: 3,
      location_id: 3,
      type: 'Trụ, cụm pano',
      width: 100,
      height: '100',
      contract_end_date: '2023-05-05T02:57:31Z',
      contract_start_date: '2023-05-05T02:57:31Z',
      company: 1,
      amount: '1 trụ/bảng',
    },
    {
      id: 4,
      location_id: 1,
      type: 'Trụ',
      width: 90,
      height: '15',
      contract_end_date: '2023-11-23T02:57:31Z',
      contract_start_date: '2023-05-05T02:57:31Z',
      company: 1,
      amount: '1 trụ/bảng',
    },
  ],
};

export {
  adsBoardTestData,
  districtTestData,
  locationTestData,
  reportTestData,
  wardTestData,
};
