const reportTestData = {
  reports: [
    {
      id: 1,
      report_form: 'troubleshooting',
      username: 'Nguyen Van A',
      email: 'nguyenvana@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 1,
      type: 'location',
      status: 'not_resolved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
    },
    {
      id: 2,
      report_form: 'report',
      username: 'Nguyen Van B',
      email: 'nguyenvanb@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 2,
      type: 'location',
      status: 'not_resolved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
    },
    {
      id: 3,
      report_form: 'suggest',
      username: 'Nguyen Van C',
      email: 'nguyenvanc@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 3,
      type: 'location',
      status: 'not_resolved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
    },
    {
      id: 4,
      report_form: 'troubleshooting',
      username: 'Tran Thi A',
      email: 'nguyenvana@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 1,
      type: 'location',
      status: 'solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
    },
    {
      id: 5,
      report_form: 'report',
      username: 'Tran Thi B',
      email: 'nguyenvanb@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 2,
      type: 'location',
      status: 'solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
    },
    {
      id: 6,
      report_form: 'suggest',
      username: 'Tran Thi C',
      email: 'nguyenvanc@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 3,
      type: 'location',
      status: 'solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
    },
    {
      id: 7,
      report_form: 'troubleshooting',
      username: 'Nguyen Van A',
      email: 'nguyenvana@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 1,
      type: 'ads_board',
      status: 'not_resolved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
    },
    {
      id: 8,
      report_form: 'report',
      username: 'Nguyen Van B',
      email: 'nguyenvanb@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 2,
      type: 'ads_board',
      status: 'not_resolved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
    },
    {
      id: 9,
      report_form: 'suggest',
      username: 'Nguyen Van C',
      email: 'nguyenvanc@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 3,
      type: 'ads_board',
      status: 'not_resolved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
    },
    {
      id: 10,
      report_form: 'troubleshooting',
      username: 'Tran Thi A',
      email: 'nguyenvana@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 1,
      type: 'ads_board',
      status: 'solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
    },
    {
      id: 11,
      report_form: 'report',
      username: 'Tran Thi B',
      email: 'nguyenvanb@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 2,
      type: 'ads_board',
      status: 'solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
    },
    {
      id: 12,
      report_form: 'suggest',
      username: 'Tran Thi C',
      email: 'nguyenvanc@gmail.com',
      phone_number: '0912345678',
      report_content: 'Can giup do',
      related_to: 3,
      type: 'ads_board',
      status: 'solved',
      operation: '',
      created_at: '2023-05-05T02:57:31Z',
    },
  ],
};

const locationTestData = {
  locations: [
    {
      id: 1,
      latitude: 10.7629462525597,
      longtitude: 106.6824931286189,
      address: '227 Đ. Nguyễn Văn Cừ',
      ward_id: 4,
      area_type: '',
      ads_type: '',
      image:
        'https://lh5.googleusercontent.com/p/AF1QipMclCpI1Ksxue8H_vB566QeSpmA1USCh4CFprFc=w408-h306-k-no',
      is_planned: false,
      isSolvedAll: false,
    },
    {
      id: 2,
      latitude: 10.762881421075154,
      longtitude: 106.68632355086243,
      address: '252 Đ. Nguyễn Trãi',
      ward_id: 4,
      area_type: '',
      ads_type: '',
      image:
        'https://lh5.googleusercontent.com/p/AF1QipMfSoB9juvelPtNK6XMFDxhM7Fj89SNSvrJA4gq=w408-h306-k-no',
      is_planned: false,
      isSolvedAll: true,
    },
    {
      id: 3,
      latitude: 10.76157111596576,
      longtitude: 106.68220011223177,
      address: '280 Đ. An Dương Vương',
      ward_id: 6,
      area_type: '',
      ads_type: '',
      image:
        'https://lh5.googleusercontent.com/p/AF1QipORTOmaH25ZBHXe1GDWkosGGB4VwYzo7iqfqBHj=w408-h307-k-no',
      is_planned: false,
      isSolvedAll: true,
    },
  ],
};

const wardTestData = {
  wards: [
    {
      id: 1,
      district_id: 5,
      name: 'Phường 1',
    },
    {
      id: 2,
      district_id: 5,
      name: 'Phường 2',
    },
    {
      id: 3,
      district_id: 5,
      name: 'Phường 3',
    },
    {
      id: 4,
      district_id: 5,
      name: 'Phường 4',
    },
    {
      id: 5,
      district_id: 5,
      name: 'Phường 5',
    },
    {
      id: 6,
      district_id: 1,
      name: 'Phường Nguyễn Cư Trinh',
    },
  ],
};

const districtTestData = {
  district: [
    {
      id: 1,
      name: 'Quận 1',
    },
    {
      id: 2,
      name: 'Quận 2',
    },
    {
      id: 3,
      name: 'Quận 3',
    },
    {
      id: 4,
      name: 'Quận 4',
    },
    {
      id: 5,
      name: 'Quận 5',
    },
  ],
};

const adsBoardTestData = {
  ads_boards: [
    {
      id: 1,
      location_id: 1,
      type: '',
      width: 100,
      height: '100',
      contract_end_date: '2023-05-05T02:57:31Z',
      contract_start_date: '2023-05-05T02:57:31Z',
      company: 1,
    },
    {
      id: 2,
      location_id: 2,
      type: '',
      width: 100,
      height: '100',
      contract_end_date: '2023-05-05T02:57:31Z',
      contract_start_date: '2023-05-05T02:57:31Z',
      company: 1,
    },
    {
      id: 3,
      location_id: 3,
      type: '',
      width: 100,
      height: '100',
      contract_end_date: '2023-05-05T02:57:31Z',
      contract_start_date: '2023-05-05T02:57:31Z',
      company: 1,
    },
  ],
};

export {
  adsBoardTestData,
  districtTestData,
  locationTestData,
  reportTestData,
  wardTestData,
};
